/** Extended A/C SEO keywords — PL source list + RU / EN / UK equivalents */

export const acSeoKeywordsPl = [
  "naprawa klimatyzacji samochodowej Warszawa",
  "serwis klimatyzacji samochodowej Warszawa",
  "nabijanie klimatyzacji Warszawa",
  "napełnianie klimatyzacji samochodowej",
  "klimatyzacja samochodowa serwis",
  "klimatyzacja auto Warszawa",
  "klimatyzacja samochodowa naprawa",
  "odgrzybianie klimatyzacji",
  "diagnostyka klimatyzacji samochodowej",
  "sprawdzenie klimatyzacji samochodowej",
  "klimatyzacja samochodowa od ręki",
  "serwis klimatyzacji bez kolejki",
  "nabijanie klimatyzacji od ręki",
  "szybka naprawa klimatyzacji",
  "ekspresowy serwis klimatyzacji",
  "klimatyzacja samochodowa dziś",
  "klimatyzacja samochodowa tego samego dnia",
  "szybkie nabijanie klimatyzacji",
  "serwis klimatyzacji natychmiast",
  "klimatyzacja bez czekania",
  "klimatyzacja samochodowa Warszawa Włochy",
  "klimatyzacja Włochy",
  "klimatyzacja Ochota",
  "klimatyzacja Mokotów",
  "klimatyzacja Ursynów",
  "klimatyzacja Bemowo",
  "klimatyzacja Raszyn",
  "klimatyzacja Piaseczno",
  "nabijanie klimatyzacji Aleja Krakowska",
  "serwis klimatyzacji Warszawa południe",
  "wymiana sprężarki klimatyzacji",
  "naprawa sprężarki klimatyzacji",
  "wymiana chłodnicy klimatyzacji",
  "wymiana skraplacza klimatyzacji",
  "uszczelnienie klimatyzacji",
  "wykrywanie nieszczelności klimatyzacji",
  "test szczelności klimatyzacji",
  "diagnostyka szczelności klimatyzacji",
  "barwnik UV klimatyzacja",
  "próżnia klimatyzacji",
  "odzysk czynnika chłodniczego",
  "uzupełnianie czynnika chłodniczego",
  "wymiana osuszacza klimatyzacji",
  "wymiana zaworu rozprężnego",
  "wymiana przewodu klimatyzacji",
  "spawanie przewodów klimatyzacji",
  "naprawa rurki klimatyzacji",
  "spawanie aluminium klimatyzacja",
  "wymiana oleju sprężarki klimatyzacji",
  "ozonowanie klimatyzacji",
  "dezynfekcja klimatyzacji",
  "czyszczenie klimatyzacji samochodowej",
  "odgrzybianie klimatyzacji samochodowej",
  "klimatyzacja R134a",
  "nabijanie R134a",
  "czynnik R134a",
  "klimatyzacja R1234yf",
  "nabijanie R1234yf",
  "serwis R1234yf",
  "klimatyzacja nie chłodzi",
  "klimatyzacja słabo chłodzi",
  "klimatyzacja nie działa",
  "klimatyzacja przestała chłodzić",
  "klimatyzacja dmucha ciepłym powietrzem",
  "klimatyzacja nie włącza się",
  "klimatyzacja śmierdzi",
  "wyciek klimatyzacji",
  "brak czynnika klimatyzacji",
  "klimatyzacja BMW",
  "klimatyzacja Audi",
  "klimatyzacja Mercedes",
  "klimatyzacja Volkswagen",
  "klimatyzacja Skoda",
  "klimatyzacja Toyota",
  "klimatyzacja Honda",
  "klimatyzacja Ford",
  "klimatyzacja Opel",
  "klimatyzacja Peugeot",
  "klimatyzacja Renault",
  "klimatyzacja Nissan",
  "klimatyzacja Mazda",
  "klimatyzacja Kia",
  "klimatyzacja Hyundai",
  "klimatyzacja Volvo",
  "klimatyzacja Seat",
  "klimatyzacja Lexus",
  "klimatyzacja Porsche",
  "tani serwis klimatyzacji Warszawa",
  "ile kosztuje nabijanie klimatyzacji",
  "cena nabijania klimatyzacji",
  "promocja klimatyzacja samochodowa",
  "profesjonalny serwis klimatyzacji",
  "najlepszy serwis klimatyzacji Warszawa",
  "warsztat klimatyzacji samochodowej",
  "mechanik klimatyzacji Warszawa",
  "serwis klimatyzacji 24h",
  "awaryjna naprawa klimatyzacji",
  "nabijanie klimatyzacji blisko mnie",
  "klimatyzacja samochodowa blisko mnie",
  "klimatyzacja samochodowa Warszawa od ręki",
  "szybki serwis klimatyzacji Warszawa",
  "naprawa klimatyzacji bez kolejki",
  "klimatyzacja samochodowa z gwarancją",
  "serwis klimatyzacji premium",
  "klimatyzacja samochodowa profesjonalnie",
  "kontrola klimatyzacji samochodowej",
  "kontrola ciśnienia klimatyzacji",
  "układ klimatyzacji samochodowej",
  "kompresor klimatyzacji",
  "sprężarka klimatyzacji",
  "czynnik chłodniczy",
  "chłodzenie samochodu",
  "klimatyzacja w aucie",
  "serwis AC samochód",
  "nabijanie klimatyzacji R134a Warszawa",
  "nabijanie klimatyzacji R1234yf Warszawa",
  "naprawa klimatyzacji osobowe",
  "klimatyzacja do samochodów osobowych",
  "klimatyzacja samochodowa Warszawa Aleja Krakowska",
  "BESS MOTORS klimatyzacja",
  "Bess Motors klimatyzacja",
  "klimatyzacja samochodowa Warszawa Włochy bez kolejki",
  "serwis klimatyzacji Aleja Krakowska 48/52 Warszawa",
] as const;

export const acSeoKeywordsRu = [
  "ремонт автокондиционера Варшава",
  "сервис кондиционера автомобиля Варшава",
  "заправка кондиционера Варшава",
  "заправка автокондиционера",
  "сервис автокондиционера",
  "кондиционер авто Варшава",
  "ремонт автомобильного кондиционера",
  "антигрибок кондиционера",
  "диагностика кондиционера автомобиля",
  "проверка кондиционера автомобиля",
  "кондиционер сразу на месте",
  "сервис кондиционера без очереди",
  "заправка кондиционера сразу",
  "быстрый ремонт кондиционера",
  "экспресс-сервис кондиционера",
  "кондиционер сегодня",
  "кондиционер в тот же день",
  "быстрая заправка кондиционера",
  "сервис кондиционера немедленно",
  "кондиционер без ожидания",
  "кондиционер Варшава Włochy",
  "кондиционер Włochy",
  "кондиционер Ochota",
  "кондиционер Мокотów",
  "кондиционер Урсынów",
  "кондиционер Bemowo",
  "кондиционер Raszyn",
  "кондиционер Piaseczno",
  "заправка кондиционера Aleja Krakowska",
  "сервис кондиционера юг Варшавы",
  "замена компрессора кондиционера",
  "ремонт компрессора кондиционера",
  "замена радиатора кондиционера",
  "замена конденсора кондиционера",
  "уплотнение кондиционера",
  "поиск утечки кондиционера",
  "тест герметичности кондиционера",
  "диагностика герметичности кондиционера",
  "UV краситель кондиционер",
  "вакуумирование кондиционера",
  "отбор хладагента",
  "дозаправка хладагента",
  "замена осушителя кондиционера",
  "замена ТРВ кондиционера",
  "замена трубок кондиционера",
  "сварка трубок кондиционера",
  "ремонт трубки кондиционера",
  "сварка алюминия кондиционер",
  "замена масла компрессора кондиционера",
  "озонирование кондиционера",
  "дезинфекция кондиционера",
  "чистка автокондиционера",
  "антигрибок автокондиционера",
  "кондиционер R134a",
  "заправка R134a",
  "фреон R134a",
  "кондиционер R1234yf",
  "заправка R1234yf",
  "сервис R1234yf",
  "кондиционер не холодит",
  "кондиционер слабо холодит",
  "кондиционер не работает",
  "кондиционер перестал холодить",
  "кондиционер дует тёплым",
  "кондиционер не включается",
  "кондиционер пахнет",
  "утечка кондиционера",
  "нет хладагента кондиционер",
  "кондиционер BMW",
  "кондиционер Audi",
  "кондиционер Mercedes",
  "кондиционер Volkswagen",
  "кондиционер Skoda",
  "кондиционер Toyota",
  "кондиционер Honda",
  "кондиционер Ford",
  "кондиционер Opel",
  "кондиционер Peugeot",
  "кондиционер Renault",
  "кондиционер Nissan",
  "кондиционер Mazda",
  "кондиционер Kia",
  "кондиционер Hyundai",
  "кондиционер Volvo",
  "кондиционер Seat",
  "кондиционер Lexus",
  "кондиционер Porsche",
  "недорогой сервис кондиционера Варшава",
  "сколько стоит заправка кондиционера",
  "цена заправки кондиционера",
  "акция кондиционер автомобиль",
  "профессиональный сервис кондиционера",
  "лучший сервис кондиционера Варшава",
  "автосервис кондиционера",
  "мастер по кондиционеру Варшава",
  "сервис кондиционера 24h",
  "аварийный ремонт кондиционера",
  "заправка кондиционера рядом",
  "кондиционер автомобиля рядом",
  "кондиционер Варшава сразу",
  "быстрый сервис кондиционера Варшава",
  "ремонт кондиционера без очереди",
  "кондиционер с гарантией",
  "премиум сервис кондиционера",
  "кондиционер профессионально",
  "проверка кондиционера автомобиля",
  "контроль давления кондиционера",
  "система кондиционирования автомобиля",
  "компрессор кондиционера",
  "хладагент",
  "охлаждение автомобиля",
  "кондиционер в машине",
  "сервис AC автомобиль",
  "заправка R134a Варшава",
  "заправка R1234yf Варшава",
  "ремонт кондиционера легковые",
  "кондиционер для легковых авто",
  "кондиционер Aleja Krakowska Варшава",
  "BESS MOTORS кондиционер",
  "кондиционер Варшава Włochy без очереди",
  "сервис кондиционера Aleja Krakowska 48/52",
] as const;

export const acSeoKeywordsEn = [
  "car A/C repair Warsaw",
  "car air conditioning service Warsaw",
  "A/C recharge Warsaw",
  "car A/C refill",
  "car air conditioning service",
  "car A/C Warsaw",
  "car air conditioning repair",
  "A/C anti-microbial treatment",
  "car A/C diagnostics",
  "car A/C inspection",
  "A/C service on the spot",
  "A/C service no queue",
  "A/C recharge on the spot",
  "fast A/C repair",
  "express A/C service",
  "car A/C today",
  "same-day A/C service",
  "fast A/C recharge",
  "immediate A/C service",
  "A/C no waiting",
  "car A/C Warsaw Wlochy",
  "A/C Wlochy",
  "A/C Ochota",
  "A/C Mokotow",
  "A/C Ursynow",
  "A/C Bemowo",
  "A/C Raszyn",
  "A/C Piaseczno",
  "A/C recharge Aleja Krakowska",
  "A/C service south Warsaw",
  "A/C compressor replacement",
  "A/C compressor repair",
  "A/C condenser replacement",
  "A/C evaporator replacement",
  "A/C sealing",
  "A/C leak detection",
  "A/C leak test",
  "A/C leak diagnostics",
  "UV dye A/C",
  "A/C vacuum",
  "refrigerant recovery",
  "refrigerant top-up",
  "A/C dryer replacement",
  "expansion valve replacement",
  "A/C line replacement",
  "A/C pipe welding",
  "A/C pipe repair",
  "aluminium welding A/C",
  "compressor oil change A/C",
  "A/C ozone treatment",
  "A/C disinfection",
  "car A/C cleaning",
  "car A/C anti-mould",
  "A/C R134a",
  "R134a recharge",
  "R134a refrigerant",
  "A/C R1234yf",
  "R1234yf recharge",
  "R1234yf service",
  "A/C not cooling",
  "A/C weak cooling",
  "A/C not working",
  "A/C stopped cooling",
  "A/C blows warm air",
  "A/C won't turn on",
  "A/C bad smell",
  "A/C leak",
  "low refrigerant A/C",
  "BMW A/C service",
  "Audi A/C service",
  "Mercedes A/C service",
  "Volkswagen A/C service",
  "Skoda A/C service",
  "Toyota A/C service",
  "Honda A/C service",
  "Ford A/C service",
  "Opel A/C service",
  "Peugeot A/C service",
  "Renault A/C service",
  "Nissan A/C service",
  "Mazda A/C service",
  "Kia A/C service",
  "Hyundai A/C service",
  "Volvo A/C service",
  "Seat A/C service",
  "Lexus A/C service",
  "Porsche A/C service",
  "cheap A/C service Warsaw",
  "A/C recharge cost",
  "A/C recharge price",
  "A/C promo car",
  "professional A/C service",
  "best A/C service Warsaw",
  "car A/C workshop",
  "A/C mechanic Warsaw",
  "A/C service 24h",
  "emergency A/C repair",
  "A/C recharge near me",
  "car A/C near me",
  "car A/C Warsaw on the spot",
  "fast A/C service Warsaw",
  "A/C repair no queue",
  "car A/C with warranty",
  "premium A/C service",
  "professional car A/C",
  "car A/C check",
  "A/C pressure check",
  "car air conditioning system",
  "A/C compressor",
  "refrigerant",
  "car cooling",
  "A/C in car",
  "car AC service",
  "R134a recharge Warsaw",
  "R1234yf recharge Warsaw",
  "passenger car A/C repair",
  "A/C for passenger cars",
  "car A/C Aleja Krakowska Warsaw",
  "BESS MOTORS A/C",
  "car A/C Warsaw Wlochy no queue",
  "A/C service Aleja Krakowska 48/52 Warsaw",
] as const;

export const acSeoKeywordsUk = [
  "ремонт автокондиціонера Варшава",
  "сервіс кондиціонера автомобіля Варшава",
  "заправка кондиціонера Варшава",
  "заправка автокондиціонера",
  "сервіс автокондиціонера",
  "кондиціонер авто Варшава",
  "ремонт автомобільного кондиціонера",
  "антигрибок кондиціонера",
  "діагностика кондиціонера автомобіля",
  "перевірка кондиціонера автомобіля",
  "кондиціонер одразу на місці",
  "сервіс кондиціонера без черги",
  "заправка кондиціонера одразу",
  "швидкий ремонт кондиціонера",
  "експрес-сервіс кондиціонера",
  "кондиціонер сьогодні",
  "кондиціонер того ж дня",
  "швидка заправка кондиціонера",
  "сервіс кондиціонера негайно",
  "кондиціонер без очікування",
  "кондиціонер Варшава Wlochy",
  "кондиціонер Wlochy",
  "кондиціонер Ochota",
  "кондиціонер Mokotów",
  "кондиціонер Ursynów",
  "кондиціонер Bemowo",
  "кондиціонер Raszyn",
  "кондиціонер Piaseczno",
  "заправка кондиціонера Aleja Krakowska",
  "сервіс кондиціонера південь Варшави",
  "заміна компресора кондиціонера",
  "ремонт компресора кондиціонера",
  "заміна радіатора кондиціонера",
  "заміна конденсора кондиціонера",
  "герметизація кондиціонера",
  "пошук витоку кондиціонера",
  "тест герметичності кондиціонера",
  "діагностика герметичності кондиціонера",
  "UV барвник кондиціонер",
  "вакуумування кондиціонера",
  "відбір холодоагенту",
  "дозаправка холодоагенту",
  "заміна осушувача кондиціонера",
  "заміна ТРВ кондиціонера",
  "заміна трубок кондиціонера",
  "зварювання трубок кондиціонера",
  "ремонт трубки кондиціонера",
  "зварювання алюмінію кондиціонер",
  "заміна масла компресора кондиціонера",
  "озонування кондиціонера",
  "дезінфекція кондиціонера",
  "чистка автокондиціонера",
  "антигрибок автокондиціонера",
  "кондиціонер R134a",
  "заправка R134a",
  "фреон R134a",
  "кондиціонер R1234yf",
  "заправка R1234yf",
  "сервіс R1234yf",
  "кондиціонер не холодить",
  "кондиціонер слабо холодить",
  "кондиціонер не працює",
  "кондиціонер перестав холодити",
  "кондиціонер дме теплим",
  "кондиціонер не вмикається",
  "кондиціонер пахне",
  "витік кондиціонера",
  "немає холодоагенту кондиціонер",
  "кондиціонер BMW",
  "кондиціонер Audi",
  "кондиціонер Mercedes",
  "кондиціонер Volkswagen",
  "кондиціонер Skoda",
  "кондиціонер Toyota",
  "кондиціонер Honda",
  "кондиціонер Ford",
  "кондиціонер Opel",
  "кондиціонер Peugeot",
  "кондиціонер Renault",
  "кондиціонер Nissan",
  "кондиціонер Mazda",
  "кондиціонер Kia",
  "кондиціонер Hyundai",
  "кондиціонер Volvo",
  "кондиціонер Seat",
  "кондиціонер Lexus",
  "кондиціонер Porsche",
  "дешевий сервіс кондиціонера Варшава",
  "скільки коштує заправка кондиціонера",
  "ціна заправки кондиціонера",
  "акція кондиціонер автомобіль",
  "професійний сервіс кондиціонера",
  "найкращий сервіс кондиціонера Варшава",
  "автосервіс кондиціонера",
  "майстер з кондиціонера Варшава",
  "сервіс кондиціонера 24h",
  "аварійний ремонт кондиціонера",
  "заправка кондиціонера поруч",
  "кондиціонер автомобіля поруч",
  "кондиціонер Варшава одразу",
  "швидкий сервіс кондиціонера Варшава",
  "ремонт кондиціонера без черги",
  "кондиціонер з гарантією",
  "преміум сервіс кондиціонера",
  "кондиціонер професійно",
  "перевірка кондиціонера автомобіля",
  "контроль тиску кондиціонера",
  "система кондиціонування автомобіля",
  "компресор кондиціонера",
  "холодоагент",
  "охолодження автомобіля",
  "кондиціонер в авто",
  "сервіс AC автомобіль",
  "заправка R134a Варшава",
  "заправка R1234yf Варшава",
  "ремонт кондиціонера легкові",
  "кондиціонер для легкових авто",
  "кондиціонер Aleja Krakowska Варшава",
  "BESS MOTORS кондиціонер",
  "кондиціонер Варшава Wlochy без черги",
  "сервіс кондиціонера Aleja Krakowska 48/52",
] as const;

/** All A/C SEO keywords — PL + RU + EN + UK (deduplicated) */
export const acSeoKeywordsAll: string[] = [
  ...new Set([
    ...acSeoKeywordsPl,
    ...acSeoKeywordsRu,
    ...acSeoKeywordsEn,
    ...acSeoKeywordsUk,
  ]),
];

const AC_REPAIR_KEY_HINTS = [
  "naprawa",
  "repair",
  "wymiana",
  "replacement",
  "spawanie",
  "welding",
  "szczelno",
  "leak",
  "sprężark",
  "compressor",
  "chłodnic",
  "condenser",
  "skraplacz",
  "osuszacz",
  "dryer",
  "przewod",
  "line",
  "rur",
  "pipe",
  "ремонт",
  "замена",
  "сварк",
  "утеч",
  "компрессор",
  "радиатор",
  "труб",
  "ремонт",
  "заміна",
  "звар",
  "витік",
  "компресор",
  "радіатор",
];

function matchesRepairKeyword(kw: string): boolean {
  const lower = kw.toLowerCase();
  return AC_REPAIR_KEY_HINTS.some((hint) => lower.includes(hint));
}

/** Keywords for `/klimatyzacja` landing meta */
export function acSeoKeywordsForRechargeLanding(): string[] {
  return acSeoKeywordsAll;
}

/** Keywords for `/naprawa-klimatyzacji` — repair-focused subset + full PL repair terms */
export function acSeoKeywordsForRepairLanding(): string[] {
  const repairFromAll = acSeoKeywordsAll.filter(matchesRepairKeyword);
  const repairPl = acSeoKeywordsPl.filter(matchesRepairKeyword);
  return [...new Set([...repairFromAll, ...repairPl, ...acSeoKeywordsRu.filter(matchesRepairKeyword), ...acSeoKeywordsEn.filter(matchesRepairKeyword), ...acSeoKeywordsUk.filter(matchesRepairKeyword)])];
}
