/** BESS MOTORS — официальный прайс (плакат + онлайн-запись) */

export type PriceCategoryId =
  | "diagnostic"
  | "maintenance"
  | "engine"
  | "timing"
  | "turbo"
  | "fuel"
  | "brakes"
  | "suspension"
  | "transmission"
  | "electrical"
  | "ac"
  | "cooling"
  | "emissions"
  | "exhaust"
  | "tires"
  | "chip"
  | "extra";

export type PriceUnit =
  | "fixed"
  | "per_cylinder"
  | "per_wheel"
  | "per_100g"
  | "tire_change_cast"
  | "tire_change_steel"
  | "free";

export interface PriceListItem {
  id: string;
  categoryId: PriceCategoryId;
  namePl: string;
  nameRu: string;
  basePrice: number;
  unit: PriceUnit;
  priceFrom?: boolean;
  minQty?: number;
  maxQty?: number;
}

export const HOURLY_RATE_PLN = 250;

export const priceCategories: { id: PriceCategoryId; namePl: string; nameRu: string }[] = [
  { id: "diagnostic", namePl: "Diagnostyka", nameRu: "Диагностика" },
  { id: "maintenance", namePl: "Obsługa techniczna", nameRu: "Техобслуживание" },
  { id: "engine", namePl: "Silnik", nameRu: "Двигатель" },
  { id: "timing", namePl: "Rozrząd / łańcuch", nameRu: "ГРМ / цепь" },
  { id: "turbo", namePl: "Turbosprężarki", nameRu: "Турбины" },
  { id: "fuel", namePl: "Układ paliwowy", nameRu: "Топливная система" },
  { id: "brakes", namePl: "Układ hamulcowy", nameRu: "Тормозная система" },
  { id: "suspension", namePl: "Zawieszenie", nameRu: "Подвеска" },
  { id: "transmission", namePl: "Skrzynia / napęd", nameRu: "КПП / привод" },
  { id: "electrical", namePl: "Elektryka", nameRu: "Электрика" },
  { id: "ac", namePl: "Klimatyzacja", nameRu: "Кондиционер" },
  { id: "cooling", namePl: "Chłodzenie", nameRu: "Охлаждение" },
  { id: "emissions", namePl: "DPF / EGR / AdBlue", nameRu: "DPF / EGR / AdBlue" },
  { id: "exhaust", namePl: "Układ wydechowy", nameRu: "Выхлопная система" },
  { id: "tires", namePl: "Wulkanizacja", nameRu: "Шиномонтаж" },
  { id: "chip", namePl: "Chip tuning", nameRu: "Chip tuning" },
  { id: "extra", namePl: "Usługi dodatkowe", nameRu: "Дополнительно" },
];

/** Примечания внизу прайса (не в корзине) */
export const priceListFooterNotes: { pl: string; ru: string }[] = [
  {
    pl: "Norma-godzina mechanika: 250 zł/h (prace rozliczane godzinowo według wyceny).",
    ru: "Норма-час механика: 250 zł/ч (работы по часам по смете).",
  },
  {
    pl: "Pilne zlecenia: +30% do ceny usługi.",
    ru: "Срочные работы: +30% к стоимости услуги.",
  },
  {
    pl: "Auta premium / sport: +20% do ceny usługi.",
    ru: "Premium / спорт авто: +20% к стоимости услуги.",
  },
  {
    pl: "Ceny „od” — ostateczny koszt po diagnostyce i weryfikacji części.",
    ru: "Цены «от» — итоговая стоимость после диагностики и подбора запчастей.",
  },
];

export const priceListItems: PriceListItem[] = [
  // —— Diagnostyka ——
  {
    id: "computer_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka komputerowa",
    nameRu: "Компьютерная диагностика",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "premium_diag",
    categoryId: "diagnostic",
    namePl: "Kompleksowa diagnostyka premium",
    nameRu: "Комплексная premium-диагностика",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "check_engine",
    categoryId: "diagnostic",
    namePl: "Diagnostyka Check Engine",
    nameRu: "Диагностика Check Engine",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "read_codes",
    categoryId: "diagnostic",
    namePl: "Odczyt błędów",
    nameRu: "Считывание ошибок",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "clear_codes",
    categoryId: "diagnostic",
    namePl: "Kasowanie błędów",
    nameRu: "Сброс ошибок",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "engine_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka silnika",
    nameRu: "Диагностика двигателя",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "suspension_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka zawieszenia",
    nameRu: "Диагностика подвески",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka układu hamulcowego",
    nameRu: "Диагностика тормозной системы",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka klimatyzacji",
    nameRu: "Диагностика кондиционера",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Obsługa techniczna ——
  {
    id: "oil_filter",
    categoryId: "maintenance",
    namePl: "Wymiana oleju i filtra oleju",
    nameRu: "Замена масла и масляного фильтра",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cabin_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra kabinowego",
    nameRu: "Замена салонного фильтра",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "air_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra powietrza",
    nameRu: "Замена воздушного фильтра",
    basePrice: 30,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "fuel_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra paliwa",
    nameRu: "Замена топливного фильтра",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "spark_plugs",
    categoryId: "maintenance",
    namePl: "Wymiana świec zapłonowych",
    nameRu: "Замена свечей зажигания",
    basePrice: 50,
    unit: "per_cylinder",
    priceFrom: true,
    minQty: 3,
    maxQty: 12,
  },
  {
    id: "glow_plugs",
    categoryId: "maintenance",
    namePl: "Wymiana świec żarowych",
    nameRu: "Замена свечей накала",
    basePrice: 80,
    unit: "per_cylinder",
    priceFrom: true,
    minQty: 3,
    maxQty: 12,
  },
  {
    id: "gearbox_oil_manual",
    categoryId: "maintenance",
    namePl: "Wymiana oleju skrzyni manualnej",
    nameRu: "Замена масла МКПП",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_oil_auto",
    categoryId: "maintenance",
    namePl: "Wymiana oleju skrzyni automatycznej",
    nameRu: "Замена масла АКПП",
    basePrice: 500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_oil_dsg",
    categoryId: "maintenance",
    namePl: "Wymiana oleju DSG",
    nameRu: "Замена масла DSG",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "power_steering_fluid",
    categoryId: "maintenance",
    namePl: "Wymiana płynu wspomagania",
    nameRu: "Замена жидкости ГУР",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Silnik ——
  {
    id: "engine_remove",
    categoryId: "engine",
    namePl: "Demontaż / montaż silnika",
    nameRu: "Снятие / установка двигателя",
    basePrice: 2500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "engine_overhaul",
    categoryId: "engine",
    namePl: "Remont silnika (kapitalny)",
    nameRu: "Капитальный ремонт двигателя",
    basePrice: 6000,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "head_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki głowicy",
    nameRu: "Замена прокладки ГБЦ",
    basePrice: 1800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "valve_cover_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki pokrywy zaworów",
    nameRu: "Замена прокладки клапанной крышки",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "oil_pan_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki miski olejowej",
    nameRu: "Замена прокладки поддона",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "crank_seal",
    categoryId: "engine",
    namePl: "Wymiana uszczelniaczy wału korbowego",
    nameRu: "Замена сальников коленвала",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "engine_mount",
    categoryId: "engine",
    namePl: "Wymiana poduszki silnika",
    nameRu: "Замена подушек двигателя",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "intercooler",
    categoryId: "engine",
    namePl: "Wymiana intercoolera",
    nameRu: "Замена интеркулера",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Rozrząd ——
  {
    id: "timing_belt",
    categoryId: "timing",
    namePl: "Wymiana paska rozrządu",
    nameRu: "Замена ремня ГРМ",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain",
    categoryId: "timing",
    namePl: "Wymiana łańcucha rozrządu",
    nameRu: "Замена цепи ГРМ",
    basePrice: 1400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain_bmw",
    categoryId: "timing",
    namePl: "Łańcuch rozrządu — silniki BMW",
    nameRu: "Цепь ГРМ — двигатели BMW",
    basePrice: 3100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain_vag",
    categoryId: "timing",
    namePl: "Łańcuch rozrządu — grupa VAG",
    nameRu: "Цепь ГРМ — группа VAG",
    basePrice: 1800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "water_pump",
    categoryId: "timing",
    namePl: "Wymiana pompy wody",
    nameRu: "Замена помпы",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Turbo ——
  {
    id: "turbo_remove",
    categoryId: "turbo",
    namePl: "Demontaż / montaż turbosprężarki",
    nameRu: "Снятие / установка турбины",
    basePrice: 600,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "turbo_replace",
    categoryId: "turbo",
    namePl: "Wymiana turbosprężarki",
    nameRu: "Замена турбины",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "turbo_regen",
    categoryId: "turbo",
    namePl: "Regeneracja turbosprężarki",
    nameRu: "Регенерация турбины",
    basePrice: 1000,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Paliwo ——
  {
    id: "fuel_hp_pump",
    categoryId: "fuel",
    namePl: "Wymiana pompy wysokiego ciśnienia",
    nameRu: "Замена ТНВД",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_replace",
    categoryId: "fuel",
    namePl: "Wymiana wtryskiwacza",
    nameRu: "Замена форсунки",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_coding",
    categoryId: "fuel",
    namePl: "Kodowanie wtryskiwaczy",
    nameRu: "Кодирование форсунок",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_clean",
    categoryId: "fuel",
    namePl: "Czyszczenie wtryskiwaczy",
    nameRu: "Чистка форсунок",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "fuel_pump",
    categoryId: "fuel",
    namePl: "Wymiana pompy paliwa",
    nameRu: "Замена бензонасоса",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Hamulce ——
  {
    id: "brake_pads_front",
    categoryId: "brakes",
    namePl: "Wymiana klocków przednich",
    nameRu: "Замена передних колодок",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_pads_rear",
    categoryId: "brakes",
    namePl: "Wymiana klocków tylnych",
    nameRu: "Замена задних колодок",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_disc_front",
    categoryId: "brakes",
    namePl: "Wymiana tarcz i klocków przednich",
    nameRu: "Замена передних дисков и колодок",
    basePrice: 220,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_disc_rear",
    categoryId: "brakes",
    namePl: "Wymiana tarcz i klocków tylnych",
    nameRu: "Замена задних дисков и колодок",
    basePrice: 280,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "handbrake_pads",
    categoryId: "brakes",
    namePl: "Wymiana klocków ręcznego",
    nameRu: "Замена колодок ручника",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "handbrake_cables",
    categoryId: "brakes",
    namePl: "Wymiana linek ręcznego",
    nameRu: "Замена тросов ручника",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_fluid",
    categoryId: "brakes",
    namePl: "Wymiana płynu hamulcowego",
    nameRu: "Замена тормозной жидкости",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "caliper_service",
    categoryId: "brakes",
    namePl: "Serwis zacisków",
    nameRu: "Обслуживание суппортов",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_hose",
    categoryId: "brakes",
    namePl: "Wymiana przewodu hamulcowego",
    nameRu: "Замена тормозного шланга",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_cylinder",
    categoryId: "brakes",
    namePl: "Wymiana cylindra hamulcowego",
    nameRu: "Замена тормозного цилиндра",
    basePrice: 180,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_booster",
    categoryId: "brakes",
    namePl: "Wymiana wzmacniacza hamulca",
    nameRu: "Замена вакуумного усилителя",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_bleed",
    categoryId: "brakes",
    namePl: "Odpowietrzanie układu hamulcowego",
    nameRu: "Прокачка тормозной системы",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "abs_unit",
    categoryId: "brakes",
    namePl: "Serwis / naprawa modułu ABS",
    nameRu: "Сервис / ремонт блока ABS",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Zawieszenie ——
  {
    id: "shock_replace",
    categoryId: "suspension",
    namePl: "Wymiana amortyzatora",
    nameRu: "Замена амортизатора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "spring_replace",
    categoryId: "suspension",
    namePl: "Wymiana sprężyny",
    nameRu: "Замена пружины",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "arm_replace",
    categoryId: "suspension",
    namePl: "Wymiana wahacza",
    nameRu: "Замена рычага",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "bushing_replace",
    categoryId: "suspension",
    namePl: "Wymiana tulei / silentbloku",
    nameRu: "Замена сайлентблока",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ball_joint",
    categoryId: "suspension",
    namePl: "Wymiana sworznia",
    nameRu: "Замена шаровой опоры",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tie_rod",
    categoryId: "suspension",
    namePl: "Wymiana końcówki drążka kierowniczego",
    nameRu: "Замена рулевого наконечника",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "sway_bar_link",
    categoryId: "suspension",
    namePl: "Wymiana łącznika stabilizatora",
    nameRu: "Замена стойки стабилизатора",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wheel_bearing",
    categoryId: "suspension",
    namePl: "Wymiana łożyska piasty",
    nameRu: "Замена ступичного подшипника",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "steering_rack",
    categoryId: "suspension",
    namePl: "Naprawa / wymiana maglownicy",
    nameRu: "Ремонт / замена рулевой рейки",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Skrzynia ——
  {
    id: "clutch",
    categoryId: "transmission",
    namePl: "Wymiana sprzęgła",
    nameRu: "Замена сцепления",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "clutch_dsg",
    categoryId: "transmission",
    namePl: "Wymiana sprzęgła DSG",
    nameRu: "Замена сцепления DSG",
    basePrice: 1400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_replace",
    categoryId: "transmission",
    namePl: "Wymiana skrzyni biegów",
    nameRu: "Замена коробки передач",
    basePrice: 1200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cv_joint",
    categoryId: "transmission",
    namePl: "Wymiana przegubu / półosi",
    nameRu: "Замена ШРУСа / привода",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "driveshaft",
    categoryId: "transmission",
    namePl: "Wymiana wału napędowego",
    nameRu: "Замена карданного вала",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Elektryka ——
  {
    id: "electric_fault",
    categoryId: "electrical",
    namePl: "Szukanie usterek elektrycznych",
    nameRu: "Поиск электрических неисправностей",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wiring_repair",
    categoryId: "electrical",
    namePl: "Naprawa instalacji elektrycznej",
    nameRu: "Ремонт электропроводки",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_check",
    categoryId: "electrical",
    namePl: "Sprawdzenie akumulatora",
    nameRu: "Проверка аккумулятора",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_replace",
    categoryId: "electrical",
    namePl: "Wymiana akumulatora",
    nameRu: "Замена аккумулятора",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_coding",
    categoryId: "electrical",
    namePl: "Kodowanie akumulatora",
    nameRu: "Кодирование АКБ",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "starter_repair",
    categoryId: "electrical",
    namePl: "Naprawa rozrusznika",
    nameRu: "Ремонт стартера",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "alternator_repair",
    categoryId: "electrical",
    namePl: "Naprawa alternatora",
    nameRu: "Ремонт генератора",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parasitic_drain",
    categoryId: "electrical",
    namePl: "Szukanie ubytku prądu",
    nameRu: "Поиск утечки тока",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "camera_install",
    categoryId: "electrical",
    namePl: "Montaż kamery / rejestratora",
    nameRu: "Установка камеры / регистратора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parking_sensors",
    categoryId: "electrical",
    namePl: "Montaż czujników parkowania",
    nameRu: "Установка парктроников",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Klimatyzacja ——
  {
    id: "ac_r134a",
    categoryId: "ac",
    namePl: "Napełnianie klimatyzacji R134a",
    nameRu: "Заправка кондиционера R134a",
    basePrice: 80,
    unit: "per_100g",
    priceFrom: true,
    minQty: 1,
    maxQty: 30,
  },
  {
    id: "ac_r1234yf",
    categoryId: "ac",
    namePl: "Napełnianie klimatyzacji R1234yf",
    nameRu: "Заправка кондиционера R1234yf",
    basePrice: 100,
    unit: "per_100g",
    priceFrom: true,
    minQty: 1,
    maxQty: 30,
  },
  {
    id: "ac_leak",
    categoryId: "ac",
    namePl: "Sprawdzenie szczelności układu",
    nameRu: "Проверка герметичности системы",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_ozone",
    categoryId: "ac",
    namePl: "Ozonyzacja salonu",
    nameRu: "Озонирование салона",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_clean",
    categoryId: "ac",
    namePl: "Czyszczenie / odgrzybianie klimatyzacji",
    nameRu: "Чистка / антигрибок кондиционера",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_compressor",
    categoryId: "ac",
    namePl: "Wymiana sprężarki klimatyzacji",
    nameRu: "Замена компрессора кондиционера",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_radiator",
    categoryId: "ac",
    namePl: "Wymiana chłodnicy klimatyzacji",
    nameRu: "Замена радиатора кондиционера",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_lines",
    categoryId: "ac",
    namePl: "Wymiana przewodów klimatyzacji",
    nameRu: "Замена трубок кондиционера",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_dryer",
    categoryId: "ac",
    namePl: "Wymiana osuszacza klimatyzacji",
    nameRu: "Замена осушителя кондиционера",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Chłodzenie ——
  {
    id: "coolant",
    categoryId: "cooling",
    namePl: "Wymiana płynu chłodzącego",
    nameRu: "Замена охлаждающей жидкости",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "coolant_radiator",
    categoryId: "cooling",
    namePl: "Wymiana chłodnicy silnika",
    nameRu: "Замена радиатора охлаждения",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "coolant_hose",
    categoryId: "cooling",
    namePl: "Wymiana węża chłodzenia",
    nameRu: "Замена патрубка охлаждения",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cooling_fan",
    categoryId: "cooling",
    namePl: "Wymiana wentylatora chłodnicy",
    nameRu: "Замена вентилятора радиатора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "thermostat",
    categoryId: "cooling",
    namePl: "Wymiana termostatu",
    nameRu: "Замена термостата",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cooling_flush",
    categoryId: "cooling",
    namePl: "Płukanie układu chłodzenia",
    nameRu: "Промывка системы охлаждения",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },

  // —— DPF / EGR ——
  {
    id: "dpf_clean",
    categoryId: "emissions",
    namePl: "Czyszczenie DPF",
    nameRu: "Чистка DPF",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dpf_replace",
    categoryId: "emissions",
    namePl: "Wymiana filtra DPF",
    nameRu: "Замена сажевого фильтра DPF",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "egr_clean",
    categoryId: "emissions",
    namePl: "Czyszczenie zaworu EGR",
    nameRu: "Чистка клапана EGR",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "egr_off",
    categoryId: "emissions",
    namePl: "EGR OFF (programowanie)",
    nameRu: "EGR OFF (программирование)",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dpf_off",
    categoryId: "emissions",
    namePl: "DPF OFF (programowanie)",
    nameRu: "DPF OFF (программирование)",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "adblue_off",
    categoryId: "emissions",
    namePl: "AdBlue OFF (programowanie)",
    nameRu: "AdBlue OFF (программирование)",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Wydech ——
  {
    id: "muffler_replace",
    categoryId: "exhaust",
    namePl: "Wymiana tłumika",
    nameRu: "Замена глушителя",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cat_replace",
    categoryId: "exhaust",
    namePl: "Wymiana katalizatora",
    nameRu: "Замена катализатора",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "exhaust_weld",
    categoryId: "exhaust",
    namePl: "Spawanie układu wydechowego",
    nameRu: "Сварка выхлопной системы",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "custom_exhaust",
    categoryId: "exhaust",
    namePl: "Układ wydechowy na zamówienie",
    nameRu: "Выхлоп на заказ",
    basePrice: 1300,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Opony ——
  {
    id: "tire_change_cast_15_17",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi aluminiowe R15–R17",
    nameRu: "Комплексная замена шин — литые R15–R17",
    basePrice: 200,
    unit: "tire_change_cast",
    priceFrom: true,
  },
  {
    id: "tire_change_cast_18_20",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi aluminiowe R18–R20",
    nameRu: "Комплексная замена шин — литые R18–R20",
    basePrice: 250,
    unit: "tire_change_cast",
    priceFrom: true,
  },
  {
    id: "tire_change_steel_15_17",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi stalowe R15–R17",
    nameRu: "Комплексная замена шин — сталь R15–R17",
    basePrice: 160,
    unit: "tire_change_steel",
    priceFrom: true,
  },
  {
    id: "tire_change_steel_18_20",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi stalowe R18–R20",
    nameRu: "Комплексная замена шин — сталь R18–R20",
    basePrice: 200,
    unit: "tire_change_steel",
    priceFrom: true,
  },
  {
    id: "wheel_balance",
    categoryId: "tires",
    namePl: "Wyważanie 1 koła",
    nameRu: "Балансировка 1 колеса",
    basePrice: 15,
    unit: "per_wheel",
    priceFrom: true,
    minQty: 1,
    maxQty: 4,
  },
  {
    id: "puncture_repair",
    categoryId: "tires",
    namePl: "Naprawa przebicia",
    nameRu: "Ремонт прокола",
    basePrice: 80,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "sidewall_repair",
    categoryId: "tires",
    namePl: "Naprawa bocznego nacięcia",
    nameRu: "Ремонт бокового пореза",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "runflat_mount",
    categoryId: "tires",
    namePl: "Montaż RunFlat",
    nameRu: "Монтаж RunFlat",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "valve_replace",
    categoryId: "tires",
    namePl: "Wymiana wentyla",
    nameRu: "Замена вентиля",
    basePrice: 15,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "rim_straighten",
    categoryId: "tires",
    namePl: "Prostowanie felgi",
    nameRu: "Правка диска",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tire_storage",
    categoryId: "tires",
    namePl: "Sezonowe przechowywanie opon (komplet)",
    nameRu: "Сезонное хранение шин (комплект)",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "alignment",
    categoryId: "tires",
    namePl: "Geometria / zbieżność kół",
    nameRu: "Развал-схождение",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wheel_wash",
    categoryId: "tires",
    namePl: "Mycie kół",
    nameRu: "Мойка колёс",
    basePrice: 80,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Chip tuning ——
  {
    id: "stage1",
    categoryId: "chip",
    namePl: "Stage 1",
    nameRu: "Stage 1",
    basePrice: 1200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "stage2",
    categoryId: "chip",
    namePl: "Stage 2",
    nameRu: "Stage 2",
    basePrice: 2500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pops_bangs",
    categoryId: "chip",
    namePl: "Pops & Bangs",
    nameRu: "Pops & Bangs",
    basePrice: 600,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ecu_tune",
    categoryId: "chip",
    namePl: "Konfiguracja ECU",
    nameRu: "Настройка ECU",
    basePrice: 1500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dyno",
    categoryId: "chip",
    namePl: "Pomiar mocy na hamowni",
    nameRu: "Замер мощности на стенде",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Dodatkowe ——
  {
    id: "mobile_diag",
    categoryId: "extra",
    namePl: "Diagnostyka mobilna (wyjazd)",
    nameRu: "Выездная диагностика",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pre_sale",
    categoryId: "extra",
    namePl: "Kontrola przed sprzedażą",
    nameRu: "Предпродажная проверка",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pre_buy",
    categoryId: "extra",
    namePl: "Kontrola przed zakupem",
    nameRu: "Проверка перед покупкой",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tow",
    categoryId: "extra",
    namePl: "Laweta / pomoc drogowa",
    nameRu: "Эвакуатор / помощь на дороге",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "loaner_car",
    categoryId: "extra",
    namePl: "Samochód zastępczy",
    nameRu: "Подменный автомобиль",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parts_pick",
    categoryId: "extra",
    namePl: "Dobór części",
    nameRu: "Подбор запчастей",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "photo_report",
    categoryId: "extra",
    namePl: "Raport foto naprawy",
    nameRu: "Фотоотчёт ремонта",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "online_history",
    categoryId: "extra",
    namePl: "Historia serwisowa online",
    nameRu: "Онлайн история обслуживания",
    basePrice: 0,
    unit: "free",
  },
];

export function getPriceItem(id: string): PriceListItem | undefined {
  return priceListItems.find((i) => i.id === id);
}

export function itemsByCategory(categoryId: PriceCategoryId): PriceListItem[] {
  return priceListItems.filter((i) => i.categoryId === categoryId);
}
