/** BESS MOTORS — официальный прайс (плакат + онлайн-запись) */

import { SITE_PROMO_PERCENT } from "@/lib/promo-codes";
import { getOilBrakePromoOffer } from "@/lib/oil-brake-promo";

export type PriceCategoryId =
  | "diagnostic"
  | "maintenance"
  | "engine"
  | "timing"
  | "turbo"
  | "fuel"
  | "brakes"
  | "suspension"
  | "transmission"
  | "electrical"
  | "ac"
  | "cooling"
  | "emissions"
  | "exhaust"
  | "tires"
  | "chip"
  | "extra";

export type PriceUnit =
  | "fixed"
  | "per_cylinder"
  | "per_wheel"
  | "per_100g"
  | "tire_change_cast"
  | "tire_change_steel"
  | "free";

export interface PriceListItem {
  id: string;
  categoryId: PriceCategoryId;
  namePl: string;
  nameRu: string;
  nameEn?: string;
  nameUk?: string;
  basePrice: number;
  /** Original list price before site promo (−15%, not used for AC) */
  listPrice?: number;
  unit: PriceUnit;
  priceFrom?: boolean;
  minQty?: number;
  maxQty?: number;
}

export const HOURLY_RATE_PLN = 250;

export const priceCategories: { id: PriceCategoryId; namePl: string; nameRu: string; nameEn?: string; nameUk?: string }[] = [
  { id: "diagnostic", namePl: "Diagnostyka", nameRu: "Диагностика", nameEn: "Diagnostics", nameUk: "Діагностика" },
  { id: "maintenance", namePl: "Obsługa techniczna", nameRu: "Техобслуживание", nameEn: "Maintenance", nameUk: "Техобслуговування" },
  { id: "engine", namePl: "Silnik", nameRu: "Двигатель", nameEn: "Engine", nameUk: "Двигун" },
  { id: "timing", namePl: "Rozrząd / łańcuch", nameRu: "ГРМ / цепь", nameEn: "Timing belt / chain", nameUk: "ГРМ / ланцюг" },
  { id: "turbo", namePl: "Turbosprężarki", nameRu: "Турбины", nameEn: "Turbochargers", nameUk: "Турбіни" },
  { id: "fuel", namePl: "Układ paliwowy", nameRu: "Топливная система", nameEn: "Fuel system", nameUk: "Паливна система" },
  { id: "brakes", namePl: "Układ hamulcowy", nameRu: "Тормозная система", nameEn: "Brake system", nameUk: "Гальмівна система" },
  { id: "suspension", namePl: "Zawieszenie", nameRu: "Подвеска", nameEn: "Suspension", nameUk: "Підвіска" },
  { id: "transmission", namePl: "Skrzynia / napęd", nameRu: "КПП / привод", nameEn: "Gearbox / drivetrain", nameUk: "КПП / привід" },
  { id: "electrical", namePl: "Elektryka", nameRu: "Электрика", nameEn: "Electrics", nameUk: "Електрика" },
  { id: "ac", namePl: "Klimatyzacja", nameRu: "Кондиционер", nameEn: "Air conditioning", nameUk: "Кондиціонер" },
  { id: "cooling", namePl: "Chłodzenie", nameRu: "Охлаждение", nameEn: "Cooling", nameUk: "Охолодження" },
  { id: "emissions", namePl: "DPF / EGR / AdBlue", nameRu: "DPF / EGR / AdBlue", nameEn: "DPF / EGR / AdBlue", nameUk: "DPF / EGR / AdBlue" },
  { id: "exhaust", namePl: "Układ wydechowy", nameRu: "Выхлопная система", nameEn: "Exhaust system", nameUk: "Вихлопна система" },
  { id: "tires", namePl: "Wulkanizacja", nameRu: "Шиномонтаж", nameEn: "Tire service", nameUk: "Шиномонтаж" },
  { id: "chip", namePl: "Chip tuning", nameRu: "Chip tuning", nameEn: "Chip tuning", nameUk: "Chip tuning" },
  { id: "extra", namePl: "Usługi dodatkowe", nameRu: "Дополнительно", nameEn: "Additional services", nameUk: "Додатково" },
];

/** Примечания внизу прайса (не в корзине) */
export const priceListFooterNotes: { pl: string; ru: string; en?: string; uk?: string }[] = [
  {
    pl: "Ceny w cenniku zawierają rabat −15% (oprócz klimatyzacji). Przekreślona cena to cennik przed rabatem.",
    ru: "Цены в прайсе уже со скидкой −15% (кроме кондиционера). Зачёркнутая — прайс до скидки.",
    en: "Prices in the price list include a discount of-15% (except for air conditioning). The price strikethrough is the price list before the discount.",
    uk: "Ціни в прайс-листі вже зі знижкою −15% (крім кондиціонера). Перекреслення — прайс-лист до знижки.",
  },
  {
    pl: "Norma-godzina mechanika: 250 zł/h (prace rozliczane godzinowo według wyceny).",
    ru: "Норма-час механика: 250 zł/ч (работы по часам по смете).",
    en: "Mechanic's standard hour: PLN 250/h (works settled hourly according to the valuation).",
    uk: "Нормальна година роботи механіка: 250 зл/год (робочий час за кошторисом).",
  },
  {
    pl: "Pilne zlecenia: +30% do ceny usługi.",
    ru: "Срочные работы: +30% к стоимости услуги.",
    en: "Urgent orders: +30% to the price of the service.",
    uk: "Термінові роботи: +30% до вартості послуги.",
  },
  {
    pl: "Auta premium / sport: +20% do ceny usługi.",
    ru: "Premium / спорт авто: +20% к стоимости услуги.",
    en: "Premium / sports cars: +20% to the price of the service.",
    uk: "Преміальні / спортивні автомобілі: +20% до вартості послуги.",
  },
  {
    pl: "Ceny „od” — ostateczny koszt po diagnostyce i weryfikacji części.",
    ru: "Цены «от» — итоговая стоимость после диагностики и подбора запчастей.",
    en: "Prices \"from\" — the final cost after diagnostics and verification of the part.",
    uk: "Ціни «від» — загальна вартість після діагностики та підбору запчастин.",
  },
];

const priceListItemsCatalog: PriceListItem[] = [
  // —— Diagnostyka ——
  {
    id: "computer_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka komputerowa",
    nameRu: "Компьютерная диагностика",
    nameEn: "Computer diagnostics",
    nameUk: "Комп’ютерна діагностика",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "premium_diag",
    categoryId: "diagnostic",
    namePl: "Kompleksowa diagnostyka premium",
    nameRu: "Комплексная premium-диагностика",
    nameEn: "Comprehensive premium diagnostics",
    nameUk: "Комплексна преміальна діагностика",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "check_engine",
    categoryId: "diagnostic",
    namePl: "Diagnostyka Check Engine",
    nameRu: "Диагностика Check Engine",
    nameEn: "Check Engine diagnostics",
    nameUk: "Перевірка діагностики двигуна",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "read_codes",
    categoryId: "diagnostic",
    namePl: "Odczyt błędów",
    nameRu: "Считывание ошибок",
    nameEn: "Fault code reading",
    nameUk: "Помилка читання",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "clear_codes",
    categoryId: "diagnostic",
    namePl: "Kasowanie błędów",
    nameRu: "Сброс ошибок",
    nameEn: "Fault code clearing",
    nameUk: "Скинути помилки",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "engine_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka silnika",
    nameRu: "Диагностика двигателя",
    nameEn: "Engine diagnostics",
    nameUk: "Діагностика двигуна",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "suspension_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka zawieszenia",
    nameRu: "Диагностика подвески",
    nameEn: "Suspension diagnostics",
    nameUk: "Діагностика призупинення",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka układu hamulcowego",
    nameRu: "Диагностика тормозной системы",
    nameEn: "Brake system diagnostics",
    nameUk: "Діагностика гальм",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_diag",
    categoryId: "diagnostic",
    namePl: "Diagnostyka klimatyzacji",
    nameRu: "Диагностика кондиционера",
    nameEn: "Air conditioning diagnostics",
    nameUk: "Діагностика кондиціонерів",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Obsługa techniczna ——
  {
    id: "oil_filter",
    categoryId: "maintenance",
    namePl: "Wymiana oleju i filtra oleju",
    nameRu: "Замена масла и масляного фильтра",
    nameEn: "Changing the oil and oil filter",
    nameUk: "Заміна мастила та масляного фільтра",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cabin_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra kabinowego",
    nameRu: "Замена салонного фильтра",
    nameEn: "Replacing the cabin filter",
    nameUk: "Заміна салонного фільтра",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "air_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra powietrza",
    nameRu: "Замена воздушного фильтра",
    nameEn: "Air filter replacement",
    nameUk: "ЗАМІНА ПОВІТРЯНОГО ФІЛЬТРА",
    basePrice: 30,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "fuel_filter",
    categoryId: "maintenance",
    namePl: "Wymiana filtra paliwa",
    nameRu: "Замена топливного фильтра",
    nameEn: "Replacement, Fuel Filter",
    nameUk: "Заміна паливного фільтра",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "spark_plugs",
    categoryId: "maintenance",
    namePl: "Wymiana świec zapłonowych",
    nameRu: "Замена свечей зажигания",
    nameEn: "Spark plugs, replacement-",
    nameUk: "Заміна свічок запалювання",
    basePrice: 50,
    unit: "per_cylinder",
    priceFrom: true,
    minQty: 3,
    maxQty: 12,
  },
  {
    id: "glow_plugs",
    categoryId: "maintenance",
    namePl: "Wymiana świec żarowych",
    nameRu: "Замена свечей накала",
    nameEn: "Replacing glow plugs",
    nameUk: "Заміна свічок запалювання",
    basePrice: 80,
    unit: "per_cylinder",
    priceFrom: true,
    minQty: 3,
    maxQty: 12,
  },
  {
    id: "gearbox_oil_manual",
    categoryId: "maintenance",
    namePl: "Wymiana oleju skrzyni manualnej",
    nameRu: "Замена масла МКПП",
    nameEn: "Changing the manual box oil",
    nameUk: "Заміна мастила механічної трансмісії",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_oil_auto",
    categoryId: "maintenance",
    namePl: "Wymiana oleju skrzyni automatycznej",
    nameRu: "Замена масла АКПП",
    nameEn: "Changing the automatic transmission oil",
    nameUk: "Заміна мастила в автоматичній трансмісії",
    basePrice: 500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_oil_dsg",
    categoryId: "maintenance",
    namePl: "Wymiana oleju DSG",
    nameRu: "Замена масла DSG",
    nameEn: "Oil change",
    nameUk: "Заміна масла DSG",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "power_steering_fluid",
    categoryId: "maintenance",
    namePl: "Wymiana płynu wspomagania",
    nameRu: "Замена жидкости ГУР",
    nameEn: "Replacing the booster fluid",
    nameUk: "Заміна рідини GUR",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Silnik ——
  {
    id: "engine_remove",
    categoryId: "engine",
    namePl: "Demontaż / montaż silnika",
    nameRu: "Снятие / установка двигателя",
    nameEn: "Engine disassembly / assembly",
    nameUk: "Зняття / встановлення двигуна",
    basePrice: 2500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "engine_overhaul",
    categoryId: "engine",
    namePl: "Remont silnika (kapitalny)",
    nameRu: "Капитальный ремонт двигателя",
    nameEn: "Engine overhaul (major)",
    nameUk: "Капітальний ремонт двигуна",
    basePrice: 6000,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "head_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki głowicy",
    nameRu: "Замена прокладки ГБЦ",
    nameEn: "Replacing the head gasket",
    nameUk: "Заміна прокладки головки",
    basePrice: 1800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "valve_cover_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki pokrywy zaworów",
    nameRu: "Замена прокладки клапанной крышки",
    nameEn: "Replacing the valve cover gasket",
    nameUk: "Заміна прокладки кришки клапана",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "oil_pan_gasket",
    categoryId: "engine",
    namePl: "Wymiana uszczelki miski olejowej",
    nameRu: "Замена прокладки поддона",
    nameEn: "Replacing the oil pan gasket",
    nameUk: "Заміна ущільнювача піддонів",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "crank_seal",
    categoryId: "engine",
    namePl: "Wymiana uszczelniaczy wału korbowego",
    nameRu: "Замена сальников коленвала",
    nameEn: "Crankshaft Oil Seal Replacement",
    nameUk: "Заміна масляних ущільнень колінчастого вала",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "engine_mount",
    categoryId: "engine",
    namePl: "Wymiana poduszki silnika",
    nameRu: "Замена подушек двигателя",
    nameEn: "Replacing the engine mount",
    nameUk: "Заміна подушок двигуна",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "intercooler",
    categoryId: "engine",
    namePl: "Wymiana intercoolera",
    nameRu: "Замена интеркулера",
    nameEn: "Replacing the intercooler",
    nameUk: "Заміна інтеркулера",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Rozrząd ——
  {
    id: "timing_belt",
    categoryId: "timing",
    namePl: "Wymiana paska rozrządu",
    nameRu: "Замена ремня ГРМ",
    nameEn: "Timing Belt Replacement",
    nameUk: "Заміна ременя ГРМ",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain",
    categoryId: "timing",
    namePl: "Wymiana łańcucha rozrządu",
    nameRu: "Замена цепи ГРМ",
    nameEn: "Replacing the timing chain",
    nameUk: "Заміна ланцюга синхронізації",
    basePrice: 1400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain_bmw",
    categoryId: "timing",
    namePl: "Łańcuch rozrządu — silniki BMW",
    nameRu: "Цепь ГРМ — двигатели BMW",
    nameEn: "Timing chain — BMW engines",
    nameUk: "Ланцюг синхронізації — двигуни BMW",
    basePrice: 3100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "timing_chain_vag",
    categoryId: "timing",
    namePl: "Łańcuch rozrządu — grupa VAG",
    nameRu: "Цепь ГРМ — группа VAG",
    nameEn: "Cam chain — VAG group",
    nameUk: "Часовий ланцюг — VAG Group",
    basePrice: 1800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "water_pump",
    categoryId: "timing",
    namePl: "Wymiana pompy wody",
    nameRu: "Замена помпы",
    nameEn: "pump replacement",
    nameUk: "Заміна насоса",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Turbo ——
  {
    id: "turbo_remove",
    categoryId: "turbo",
    namePl: "Demontaż / montaż turbosprężarki",
    nameRu: "Снятие / установка турбины",
    nameEn: "Turbocharger Removal / Installation",
    nameUk: "Зняття / встановлення турбіни",
    basePrice: 600,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "turbo_replace",
    categoryId: "turbo",
    namePl: "Wymiana turbosprężarki",
    nameRu: "Замена турбины",
    nameEn: "Turbocharger Replacement",
    nameUk: "Заміна турбіни",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "turbo_regen",
    categoryId: "turbo",
    namePl: "Regeneracja turbosprężarki",
    nameRu: "Регенерация турбины",
    nameEn: "Turbocharger regeneration",
    nameUk: "Регенерація турбіни",
    basePrice: 1000,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Paliwo ——
  {
    id: "fuel_hp_pump",
    categoryId: "fuel",
    namePl: "Wymiana pompy wysokiego ciśnienia",
    nameRu: "Замена ТНВД",
    nameEn: "High Pressure Injection Pump Replacement",
    nameUk: "Заміна інжекторного насоса",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_replace",
    categoryId: "fuel",
    namePl: "Wymiana wtryskiwacza",
    nameRu: "Замена форсунки",
    nameEn: "Replacing injector",
    nameUk: "Заміна насадки",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_coding",
    categoryId: "fuel",
    namePl: "Kodowanie wtryskiwaczy",
    nameRu: "Кодирование форсунок",
    nameEn: "Injector coding",
    nameUk: "Кодування насадки",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "injector_clean",
    categoryId: "fuel",
    namePl: "Czyszczenie wtryskiwaczy",
    nameRu: "Чистка форсунок",
    nameEn: "Cleaning the injectors",
    nameUk: "Очищення форсунок",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "fuel_pump",
    categoryId: "fuel",
    namePl: "Wymiana pompy paliwa",
    nameRu: "Замена бензонасоса",
    nameEn: "Replacing the fuel pump",
    nameUk: "Заміна бензинового насоса",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Hamulce ——
  {
    id: "brake_pads_front",
    categoryId: "brakes",
    namePl: "Wymiana klocków przednich",
    nameRu: "Замена передних колодок",
    nameEn: "Replacing the front pads",
    nameUk: "Заміна передніх колодок",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_pads_rear",
    categoryId: "brakes",
    namePl: "Wymiana klocków tylnych",
    nameRu: "Замена задних колодок",
    nameEn: "Rear Pads Replacement",
    nameUk: "Заміна задніх колодок",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_disc_front",
    categoryId: "brakes",
    namePl: "Wymiana tarcz i klocków przednich",
    nameRu: "Замена передних дисков и колодок",
    nameEn: "Replacing front discs and pads",
    nameUk: "Заміна передніх дисків та колодок",
    basePrice: 220,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_disc_rear",
    categoryId: "brakes",
    namePl: "Wymiana tarcz i klocków tylnych",
    nameRu: "Замена задних дисков и колодок",
    nameEn: "Replacing the rear discs and pads",
    nameUk: "Заміна задніх дисків і колодок",
    basePrice: 280,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "handbrake_pads",
    categoryId: "brakes",
    namePl: "Wymiana klocków ręcznego",
    nameRu: "Замена колодок ручника",
    nameEn: "Replacing Manual Pads",
    nameUk: "Заміна колодок наконечника",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "handbrake_cables",
    categoryId: "brakes",
    namePl: "Wymiana linek ręcznego",
    nameRu: "Замена тросов ручника",
    nameEn: "Replacing manual cables",
    nameUk: "Заміна рукоятки каната",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_fluid",
    categoryId: "brakes",
    namePl: "Wymiana płynu hamulcowego",
    nameRu: "Замена тормозной жидкости",
    nameEn: "Brake fluid replacement",
    nameUk: "Заміна гальмівної рідини",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "caliper_service",
    categoryId: "brakes",
    namePl: "Serwis zacisków",
    nameRu: "Обслуживание суппортов",
    nameEn: "Terminal service",
    nameUk: "Технічне обслуговування штангенциркулів",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_hose",
    categoryId: "brakes",
    namePl: "Wymiana przewodu hamulcowego",
    nameRu: "Замена тормозного шланга",
    nameEn: "Replacing the brake line",
    nameUk: "Заміна гальмівного шланга",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_cylinder",
    categoryId: "brakes",
    namePl: "Wymiana cylindra hamulcowego",
    nameRu: "Замена тормозного цилиндра",
    nameEn: "Brake Cylinder Replacement",
    nameUk: "Заміна гальмівного циліндра",
    basePrice: 180,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_booster",
    categoryId: "brakes",
    namePl: "Wymiana wzmacniacza hamulca",
    nameRu: "Замена вакуумного усилителя",
    nameEn: "Brake Booster Replacement",
    nameUk: "Заміна вакуумного підсилювача",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "brake_bleed",
    categoryId: "brakes",
    namePl: "Odpowietrzanie układu hamulcowego",
    nameRu: "Прокачка тормозной системы",
    nameEn: "BLEEDING of the BRAKING SYSTEM :",
    nameUk: "Гальмівна кровотеча",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "abs_unit",
    categoryId: "brakes",
    namePl: "Serwis / naprawa modułu ABS",
    nameRu: "Сервис / ремонт блока ABS",
    nameEn: "ABS unit service / repair",
    nameUk: "Обслуговування / ремонт блоку ABS",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Zawieszenie ——
  {
    id: "shock_replace",
    categoryId: "suspension",
    namePl: "Wymiana amortyzatora",
    nameRu: "Замена амортизатора",
    nameEn: "Replacing the damper",
    nameUk: "Заміна амортизатора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "spring_replace",
    categoryId: "suspension",
    namePl: "Wymiana sprężyny",
    nameRu: "Замена пружины",
    nameEn: "Spring replacement",
    nameUk: "Заміна пружини",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "arm_replace",
    categoryId: "suspension",
    namePl: "Wymiana wahacza",
    nameRu: "Замена рычага",
    nameEn: "Swing Arm Replacement",
    nameUk: "Заміна важеля",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "bushing_replace",
    categoryId: "suspension",
    namePl: "Wymiana tulei / silentbloku",
    nameRu: "Замена сайлентблока",
    nameEn: "Replacing the sleeve / silentblock",
    nameUk: "Заміна сайлентблоку",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ball_joint",
    categoryId: "suspension",
    namePl: "Wymiana sworznia",
    nameRu: "Замена шаровой опоры",
    nameEn: "Replacing the pin",
    nameUk: "Заміна кульового шарніра",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tie_rod",
    categoryId: "suspension",
    namePl: "Wymiana końcówki drążka kierowniczego",
    nameRu: "Замена рулевого наконечника",
    nameEn: "Tie Rod End Replacement",
    nameUk: "Заміна наконечника керма",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "sway_bar_link",
    categoryId: "suspension",
    namePl: "Wymiana łącznika stabilizatora",
    nameRu: "Замена стойки стабилизатора",
    nameEn: "Stabilizer Link Replacement",
    nameUk: "Заміна стійки стабілізатора",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wheel_bearing",
    categoryId: "suspension",
    namePl: "Wymiana łożyska piasty",
    nameRu: "Замена ступичного подшипника",
    nameEn: "Replacing the hub bearing",
    nameUk: "Заміна колісного підшипника",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "steering_rack",
    categoryId: "suspension",
    namePl: "Naprawa / wymiana maglownicy",
    nameRu: "Ремонт / замена рулевой рейки",
    nameEn: "Repair / replacement of the magnum",
    nameUk: "Ремонт / заміна кермової рейки",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Skrzynia ——
  {
    id: "clutch",
    categoryId: "transmission",
    namePl: "Wymiana sprzęgła",
    nameRu: "Замена сцепления",
    nameEn: "clutch replacement",
    nameUk: "Заміна зчеплення",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "clutch_dsg",
    categoryId: "transmission",
    namePl: "Wymiana sprzęgła DSG",
    nameRu: "Замена сцепления DSG",
    nameEn: "clutch replacement",
    nameUk: "Заміна зчеплення DSG",
    basePrice: 1400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "gearbox_replace",
    categoryId: "transmission",
    namePl: "Wymiana skrzyni biegów",
    nameRu: "Замена коробки передач",
    nameEn: "Replacing the gearbox",
    nameUk: "Заміна коробки передач",
    basePrice: 1200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cv_joint",
    categoryId: "transmission",
    namePl: "Wymiana przegubu / półosi",
    nameRu: "Замена ШРУСа / привода",
    nameEn: "Replacing the joint / driveshaft",
    nameUk: "Заміна CV / приводу",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "driveshaft",
    categoryId: "transmission",
    namePl: "Wymiana wału napędowego",
    nameRu: "Замена карданного вала",
    nameEn: "Replacing the drive shaft",
    nameUk: "Заміна карданного вала",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Elektryka ——
  {
    id: "electric_fault",
    categoryId: "electrical",
    namePl: "Szukanie usterek elektrycznych",
    nameRu: "Поиск электрических неисправностей",
    nameEn: "Electrical Troubleshooting",
    nameUk: "Усунення несправностей електричної системи",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wiring_repair",
    categoryId: "electrical",
    namePl: "Naprawa instalacji elektrycznej",
    nameRu: "Ремонт электропроводки",
    nameEn: "Repair of the electrical system",
    nameUk: "Ремонт електропроводки",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_check",
    categoryId: "electrical",
    namePl: "Sprawdzenie akumulatora",
    nameRu: "Проверка аккумулятора",
    nameEn: "Checking the battery",
    nameUk: "Перевірка акумулятора",
    basePrice: 50,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_replace",
    categoryId: "electrical",
    namePl: "Wymiana akumulatora",
    nameRu: "Замена аккумулятора",
    nameEn: "Battery replacement",
    nameUk: "Заміна акумулятора",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "battery_coding",
    categoryId: "electrical",
    namePl: "Kodowanie akumulatora",
    nameRu: "Кодирование АКБ",
    nameEn: "Battery coding",
    nameUk: "Кодування акумулятора",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "starter_repair",
    categoryId: "electrical",
    namePl: "Naprawa rozrusznika",
    nameRu: "Ремонт стартера",
    nameEn: "Starter repair",
    nameUk: "Ремонт стартера",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "alternator_repair",
    categoryId: "electrical",
    namePl: "Naprawa alternatora",
    nameRu: "Ремонт генератора",
    nameEn: "Alternator repair",
    nameUk: "Ремонт генератора",
    basePrice: 450,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parasitic_drain",
    categoryId: "electrical",
    namePl: "Szukanie ubytku prądu",
    nameRu: "Поиск утечки тока",
    nameEn: "Searching for a power loss",
    nameUk: "Пошук поточних витоків",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "camera_install",
    categoryId: "electrical",
    namePl: "Montaż kamery / rejestratora",
    nameRu: "Установка камеры / регистратора",
    nameEn: "Mounting the camera / recorder",
    nameUk: "Встановлення камери / реєстратора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parking_sensors",
    categoryId: "electrical",
    namePl: "Montaż czujników parkowania",
    nameRu: "Установка парктроников",
    nameEn: "Installation of parking sensors",
    nameUk: "Встановлення паркувальних датчиків",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Klimatyzacja ——
  {
    id: "ac_hookup",
    categoryId: "ac",
    namePl: "Podłączenie układu klimatyzacji (próżnia)",
    nameRu: "Подключение системы кондиционера (вакуум)",
    nameEn: "Connection of the air conditioning system (vacuum)",
    nameUk: "Підключення системи кондиціонування (вакуум)",
    basePrice: 80,
    unit: "fixed",
    priceFrom: false,
  },
  {
    id: "ac_r134a",
    categoryId: "ac",
    namePl: "Napełnianie klimatyzacji R134a",
    nameRu: "Заправка кондиционера R134a (фреон)",
    nameEn: "Filling the air conditioner R134a",
    nameUk: "R134a Заправка кондиціонера (фреон)",
    basePrice: 50,
    unit: "per_100g",
    priceFrom: false,
    minQty: 1,
    maxQty: 30,
  },
  {
    id: "ac_r1234yf",
    categoryId: "ac",
    namePl: "Napełnianie klimatyzacji R1234yf",
    nameRu: "Заправка кондиционера R1234yf",
    nameEn: "Filling the air conditioner R1234yf",
    nameUk: "Заряджання кондиціонера R1234yf",
    basePrice: 50,
    unit: "per_100g",
    priceFrom: false,
    minQty: 1,
    maxQty: 30,
  },
  {
    id: "ac_leak",
    categoryId: "ac",
    namePl: "Sprawdzenie szczelności układu",
    nameRu: "Проверка герметичности системы",
    nameEn: "Checking the tightness of the system",
    nameUk: "Перевірка герметичності системи",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_ozone",
    categoryId: "ac",
    namePl: "Ozonyzacja salonu",
    nameRu: "Озонирование салона",
    nameEn: "Salon revitalization",
    nameUk: "Внутрішнє озонування",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_clean",
    categoryId: "ac",
    namePl: "Czyszczenie / odgrzybianie klimatyzacji",
    nameRu: "Чистка / антигрибок кондиционера",
    nameEn: "Cleaning / fumigation of air conditioning",
    nameUk: "Очищення /протигрибковий засіб кондиціонера",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_compressor",
    categoryId: "ac",
    namePl: "Wymiana sprężarki klimatyzacji",
    nameRu: "Замена компрессора кондиционера",
    nameEn: "Replacement, Air Conditioner Compressor",
    nameUk: "Заміна компресора кондиціонера",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_radiator",
    categoryId: "ac",
    namePl: "Wymiana chłodnicy klimatyzacji",
    nameRu: "Замена радиатора кондиционера",
    nameEn: "Air Conditioning Cooler Replacement",
    nameUk: "Заміна радіатора кондиціонера",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_lines",
    categoryId: "ac",
    namePl: "Wymiana przewodów klimatyzacji",
    nameRu: "Замена трубок кондиционера",
    nameEn: "Replacing the air conditioning ducts",
    nameUk: "Заміна трубок кондиціонера",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ac_dryer",
    categoryId: "ac",
    namePl: "Wymiana osuszacza klimatyzacji",
    nameRu: "Замена осушителя кондиционера",
    nameEn: "Replacing the A/C dryer",
    nameUk: "Заміна сушильної машини кондиціонера",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Chłodzenie ——
  {
    id: "coolant",
    categoryId: "cooling",
    namePl: "Wymiana płynu chłodzącego",
    nameRu: "Замена охлаждающей жидкости",
    nameEn: "CHANGINGCOOLANT -",
    nameUk: "Заміна охолоджуючої рідини",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "coolant_radiator",
    categoryId: "cooling",
    namePl: "Wymiana chłodnicy silnika",
    nameRu: "Замена радиатора охлаждения",
    nameEn: "Replacing the engine cooler",
    nameUk: "Заміна радіатора охолодження",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "coolant_hose",
    categoryId: "cooling",
    namePl: "Wymiana węża chłodzenia",
    nameRu: "Замена патрубка охлаждения",
    nameEn: "Replacing the cooling hose",
    nameUk: "Заміна охолоджуючої насадки",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cooling_fan",
    categoryId: "cooling",
    namePl: "Wymiana wentylatora chłodnicy",
    nameRu: "Замена вентилятора радиатора",
    nameEn: "Radiator Fan Replacement",
    nameUk: "Заміна радіаторного вентилятора",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "thermostat",
    categoryId: "cooling",
    namePl: "Wymiana termostatu",
    nameRu: "Замена термостата",
    nameEn: "Replacing the thermostat",
    nameUk: "Заміна термостата",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cooling_flush",
    categoryId: "cooling",
    namePl: "Płukanie układu chłodzenia",
    nameRu: "Промывка системы охлаждения",
    nameEn: "Flushing the cooling system",
    nameUk: "Промивка системи охолодження",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },

  // —— DPF / EGR ——
  {
    id: "dpf_clean",
    categoryId: "emissions",
    namePl: "Czyszczenie DPF",
    nameRu: "Чистка DPF",
    nameEn: "DPF cleaning",
    nameUk: "Очищення DPF",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dpf_replace",
    categoryId: "emissions",
    namePl: "Wymiana filtra DPF",
    nameRu: "Замена сажевого фильтра DPF",
    nameEn: "Replacement DPF",
    nameUk: "Заміна сажового фільтра DPF",
    basePrice: 800,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "egr_clean",
    categoryId: "emissions",
    namePl: "Czyszczenie zaworu EGR",
    nameRu: "Чистка клапана EGR",
    nameEn: "Cleaning the EGR valve",
    nameUk: "Очищення клапана EGR",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "egr_off",
    categoryId: "emissions",
    namePl: "EGR OFF (programowanie)",
    nameRu: "EGR OFF (программирование)",
    nameEn: "EGR off (programming)",
    nameUk: "EGR вимкнено (програмування)",
    basePrice: 700,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dpf_off",
    categoryId: "emissions",
    namePl: "DPF OFF (programowanie)",
    nameRu: "DPF OFF (программирование)",
    nameEn: "DPF off (programming)",
    nameUk: "DPF вимкнено (програмування)",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "adblue_off",
    categoryId: "emissions",
    namePl: "AdBlue OFF (programowanie)",
    nameRu: "AdBlue OFF (программирование)",
    nameEn: "AdBlue off (programming)",
    nameUk: "AdBlue вимкнено (програмування)",
    basePrice: 900,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Wydech ——
  {
    id: "muffler_replace",
    categoryId: "exhaust",
    namePl: "Wymiana tłumika",
    nameRu: "Замена глушителя",
    nameEn: "Silencer replaced",
    nameUk: "Заміна глушника",
    basePrice: 200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "cat_replace",
    categoryId: "exhaust",
    namePl: "Wymiana katalizatora",
    nameRu: "Замена катализатора",
    nameEn: "Replacing the catalytic conver",
    nameUk: "Заміна каталізатора",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "exhaust_weld",
    categoryId: "exhaust",
    namePl: "Spawanie układu wydechowego",
    nameRu: "Сварка выхлопной системы",
    nameEn: "Exhaust system welding",
    nameUk: "Зварювання вихлопної системи",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "custom_exhaust",
    categoryId: "exhaust",
    namePl: "Układ wydechowy na zamówienie",
    nameRu: "Выхлоп на заказ",
    nameEn: "Bespoke exhaust system",
    nameUk: "Спеціальний вихлоп",
    basePrice: 1300,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Opony ——
  {
    id: "tire_change_cast_15_17",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi aluminiowe R15–R17",
    nameRu: "Комплексная замена шин — литые R15–R17",
    nameEn: "Comprehensive tyre replacement — alloy wheels R15–R17",
    nameUk: "Комплексна заміна шин — Cast R15–R17",
    basePrice: 200,
    unit: "tire_change_cast",
    priceFrom: true,
  },
  {
    id: "tire_change_cast_18_20",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi aluminiowe R18–R20",
    nameRu: "Комплексная замена шин — литые R18–R20",
    nameEn: "Comprehensive tyre replacement — alloy wheels R18–R20",
    nameUk: "Комплексна заміна шин — Cast R18–R20",
    basePrice: 250,
    unit: "tire_change_cast",
    priceFrom: true,
  },
  {
    id: "tire_change_steel_15_17",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi stalowe R15–R17",
    nameRu: "Комплексная замена шин — сталь R15–R17",
    nameEn: "Comprehensive tyre replacement — steel rims R15–R17",
    nameUk: "Комплексна заміна шин — сталь R15–R17",
    basePrice: 160,
    unit: "tire_change_steel",
    priceFrom: true,
  },
  {
    id: "tire_change_steel_18_20",
    categoryId: "tires",
    namePl: "Kompleksowa wymiana opon — felgi stalowe R18–R20",
    nameRu: "Комплексная замена шин — сталь R18–R20",
    nameEn: "Comprehensive tyre replacement — steel rims R18–R20",
    nameUk: "Комплексна заміна шин — сталь R18–R20",
    basePrice: 200,
    unit: "tire_change_steel",
    priceFrom: true,
  },
  {
    id: "wheel_balance",
    categoryId: "tires",
    namePl: "Wyważanie 1 koła",
    nameRu: "Балансировка 1 колеса",
    nameEn: "1 wheel balancing",
    nameUk: "Балансування 1 колеса",
    basePrice: 15,
    unit: "per_wheel",
    priceFrom: true,
    minQty: 1,
    maxQty: 4,
  },
  {
    id: "puncture_repair",
    categoryId: "tires",
    namePl: "Naprawa przebicia",
    nameRu: "Ремонт прокола",
    nameEn: "Puncture repair",
    nameUk: "Ремонт проколів",
    basePrice: 80,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "sidewall_repair",
    categoryId: "tires",
    namePl: "Naprawa bocznego nacięcia",
    nameRu: "Ремонт бокового пореза",
    nameEn: "Side score repair",
    nameUk: "Ремонт бічного зрізу",
    basePrice: 120,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "runflat_mount",
    categoryId: "tires",
    namePl: "Montaż RunFlat",
    nameRu: "Монтаж RunFlat",
    nameEn: "Installation of RunFlat",
    nameUk: "Установка RunFlat",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "valve_replace",
    categoryId: "tires",
    namePl: "Wymiana wentyla",
    nameRu: "Замена вентиля",
    nameEn: "Replacing the valve",
    nameUk: "Заміна клапана",
    basePrice: 15,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "rim_straighten",
    categoryId: "tires",
    namePl: "Prostowanie felgi",
    nameRu: "Правка диска",
    nameEn: "Straightening the rim",
    nameUk: "Редагувати диск",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tire_storage",
    categoryId: "tires",
    namePl: "Sezonowe przechowywanie opon (komplet)",
    nameRu: "Сезонное хранение шин (комплект)",
    nameEn: "Seasonal tyre storage (set)",
    nameUk: "Сезонне зберігання шин (комплект)",
    basePrice: 100,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "alignment",
    categoryId: "tires",
    namePl: "Geometria / zbieżność kół",
    nameRu: "Развал-схождение",
    nameEn: "Geometry /wheel alignment",
    nameUk: "Згорнути конвергенцію",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "wheel_wash",
    categoryId: "tires",
    namePl: "Mycie kół",
    nameRu: "Мойка колёс",
    nameEn: "Wheel washing",
    nameUk: "Миття коліс",
    basePrice: 80,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Chip tuning ——
  {
    id: "stage1",
    categoryId: "chip",
    namePl: "Stage 1",
    nameRu: "Stage 1",
    nameEn: "Stage 1",
    nameUk: "Stage 1",
    basePrice: 1200,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "stage2",
    categoryId: "chip",
    namePl: "Stage 2",
    nameRu: "Stage 2",
    nameEn: "Stage 2",
    nameUk: "Stage 2",
    basePrice: 2500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pops_bangs",
    categoryId: "chip",
    namePl: "Pops & Bangs",
    nameRu: "Pops & Bangs",
    nameEn: "Pops & Bangs",
    nameUk: "Pops & Bangs",
    basePrice: 600,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "ecu_tune",
    categoryId: "chip",
    namePl: "Konfiguracja ECU",
    nameRu: "Настройка ECU",
    nameEn: "ECU configuration",
    nameUk: "Налаштування ECU",
    basePrice: 1500,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "dyno",
    categoryId: "chip",
    namePl: "Pomiar mocy na hamowni",
    nameRu: "Замер мощности на стенде",
    nameEn: "Measurement of power at the dynamometer",
    nameUk: "Вимірювання потужності на стенді",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },

  // —— Dodatkowe ——
  {
    id: "mobile_diag",
    categoryId: "extra",
    namePl: "Diagnostyka mobilna (wyjazd)",
    nameRu: "Выездная диагностика",
    nameEn: "Mobile diagnostics (departure)",
    nameUk: "Діагностика на місці",
    basePrice: 300,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pre_sale",
    categoryId: "extra",
    namePl: "Kontrola przed sprzedażą",
    nameRu: "Предпродажная проверка",
    nameEn: "Pre-sale inspection",
    nameUk: "Передпродажна перевірка",
    basePrice: 350,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "pre_buy",
    categoryId: "extra",
    namePl: "Kontrola przed zakupem",
    nameRu: "Проверка перед покупкой",
    nameEn: "Pre-purchase inspection",
    nameUk: "Перевірка перед купівлею",
    basePrice: 400,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "tow",
    categoryId: "extra",
    namePl: "Laweta / pomoc drogowa",
    nameRu: "Эвакуатор / помощь на дороге",
    nameEn: "Tow Truck / Roadside Assistance",
    nameUk: "Евакуатор / допомога на дорозі",
    basePrice: 250,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "loaner_car",
    categoryId: "extra",
    namePl: "Samochód zastępczy",
    nameRu: "Подменный автомобиль",
    nameEn: "Replacement car",
    nameUk: "Заміна транспортного засобу",
    basePrice: 150,
    unit: "fixed",
    priceFrom: true,
  },
  {
    id: "parts_pick",
    categoryId: "extra",
    namePl: "Dobór części",
    nameRu: "Подбор запчастей",
    nameEn: "Selection of parts",
    nameUk: "Вибір запасних частин",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "photo_report",
    categoryId: "extra",
    namePl: "Raport foto naprawy",
    nameRu: "Фотоотчёт ремонта",
    nameEn: "Photo Repair Report",
    nameUk: "Фотозвіт про ремонт",
    basePrice: 0,
    unit: "free",
  },
  {
    id: "online_history",
    categoryId: "extra",
    namePl: "Historia serwisowa online",
    nameRu: "Онлайн история обслуживания",
    nameEn: "Online Service History",
    nameUk: "Історія онлайн-служби",
    basePrice: 0,
    unit: "free",
  },
];

function withSitePromoCatalogItem(item: PriceListItem): PriceListItem {
  const special = getOilBrakePromoOffer(item.id);
  if (special) {
    return {
      ...item,
      basePrice: special.nowZl,
      listPrice: special.wasZl,
      priceFrom: false,
    };
  }
  if (item.categoryId === "ac" || item.unit === "free" || item.basePrice <= 0) {
    return item;
  }
  const basePrice = Math.round((item.basePrice * (100 - SITE_PROMO_PERCENT)) / 100);
  if (basePrice === item.basePrice) return item;
  return { ...item, listPrice: item.basePrice, basePrice };
}

/** Public price list — basePrice is the promo price; listPrice is the crossed-out “was” price. */
export const priceListItems: PriceListItem[] =
  priceListItemsCatalog.map(withSitePromoCatalogItem);

export function getPriceItem(id: string): PriceListItem | undefined {
  return priceListItems.find((i) => i.id === id);
}

export function itemsByCategory(categoryId: PriceCategoryId): PriceListItem[] {
  return priceListItems.filter((i) => i.categoryId === categoryId);
}
