export const seoFooterServiceLinks: { href: string; label: string }[] = [
  { href: "/wymiana-oleju-warszawa", label: "Wymiana oleju Warszawa" },
  { href: "/hamulce-warszawa", label: "Hamulce Warszawa" },
  { href: "/wymiana-klockow-hamulcowych-warszawa", label: "Wymiana klocków hamulcowych" },
  { href: "/diagnostyka-komputerowa-warszawa", label: "Diagnostyka komputerowa" },
  { href: "/serwis-klimatyzacji-warszawa", label: "Serwis klimatyzacji Warszawa" },
  { href: "/naprawa-zawieszenia-warszawa", label: "Naprawa zawieszenia" },
  { href: "/wulkanizacja-warszawa", label: "Wulkanizacja Warszawa" },
  { href: "/wymiana-opon-warszawa", label: "Wymiana opon Warszawa" },
  { href: "/wymiana-rozrzadu-warszawa", label: "Wymiana rozrządu" },
  { href: "/wymiana-sprzegla-warszawa", label: "Wymiana sprzęgła" },
  { href: "/wymiana-oleju-skrzynia-automatyczna-warszawa", label: "Olej skrzyni automatycznej" },
  { href: "/mechanik-warszawa-wlochy", label: "Mechanik Warszawa Włochy" },
  { href: "/mechanik-warszawa-okecie", label: "Mechanik Warszawa Okęcie" },
  { href: "/klimatyzacja", label: "Nabijanie klimatyzacji" },
  { href: "/wymiana-oleju", label: "Wymiana oleju 80 zł" },
  { href: "/hamulce", label: "Hamulce — klocki od 100 zł" },
  { href: "/opony", label: "Wulkanizacja" },
  { href: "/cennik", label: "Cennik" },
  { href: "/contacts", label: "Kontakt" },
];
